#! /usr/bin/python3.6

a = input('Digite algo: \033[30m')
print('\033[m', end='')
print('Numérico: {}'.format(a.isnumeric()))
print('Alfabético: {}'.format(a.isalpha()))
print('Alfanumérico: {}'.format(a.isalnum()))
print('Digito: {}'.format(a.isdigit()))
print('Identificador: {}'.format(a.isidentifier()))
print('Decimal: {}'.format(a.isdecimal()))
print('Caixa baixa: {}'.format(a.islower()))
print('Imprimível: {}'.format(a.isprintable()))
print('Espaço: {}'.format(a.isspace()))
print('Título: {}'.format(a.istitle()))
print('Caixa alta: {}'.format(a.isupper()))
